config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # Each user will have one pantry
  get "my_pantry", to: "pantries#show", as: :pantry
  get "shopping_list", to: "shopping_lists#show", as: :shopping_list
  patch "items/:id/add_to_list", to: "items#add_to_list", as: :add_to_list
  get "/profile", to: "pages#profile"


  resources :pantries, only: [:create]
  resources :items, only: [:new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :pantry, optional: true
  belongs_to :shopping_list, optional: true
  validates :name, presence: true
  validates :quantity, presence: true
  validates :threshold, presence: true
  validate :must_have_pantry_or_shopping_list

  private

  def must_have_pantry_or_shopping_list
    if pantry.nil? && shopping_list.nil?
      errors.add(:base, "must be associated to a pantry or shopping list")
    end
  end

end

app/models/pantry.rb
class Pantry < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true, length: { in: 6..20 }
  has_one :pantry, dependent: :destroy
  has_one :shopping_list, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:edit, :update, :destroy, :add_to_list]

  def new
    @existing_items = current_user.pantry.items.where(shopping_list: nil)
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if params[:previous_page].include? "/my_pantry"
      @item.pantry = current_user.pantry
      below_threshold?
    elsif params[:previous_page].include? "/shopping_list"
      if params[:item][:id]
        @item = Item.find(params[:item][:id])
      end
      @item.shopping_list = current_user.shopping_list
    end
    if @item.save
      redirect_to params[:previous_page]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to params[:previous_page]
    else
      render :edit
    end
  end

  def destroy
    if (request.referer.include? "/shopping_list") && @item.pantry
      @item.shopping_list = nil
      @item.save
    else
      @item.destroy
    end
    redirect_to request.referer
  end

  def add_to_list
    @item.shopping_list = current_user.shopping_list
    if @item.save
      redirect_to request.referer
      flash[:notice] = "Item added to shopping list"
    end
  end

  private

  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :quantity, :threshold)
  end

  def below_threshold?
    @item.shopping_list = current_user.shopping_list if @item.quantity <= @item.threshold
  end

  # def remove_from_list
  #   if request.referer.include? "/shopping_list"
  #     @item.shopping_list = nil
  #   else
  #     @§item.pantry = nil
  #   end
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def profile
    @user = current_user
  end
end

app/controllers/pantries_controller.rb
class PantriesController < ApplicationController
  def show
    @pantry = Pantry.find_by(user: current_user)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super do |resource|
      Pantry.create(user: resource, name: "#{resource.username}'s pantry") if resource.persisted?
      ShoppingList.create(user: resource) if resource.persisted?
    end
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def show
    @shopping_list = current_user.shopping_list
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :quantity %>
  <%= f.input :threshold %>
  <%= f.button :submit %>

  <%= hidden_field_tag :previous_page, request.referer %>
<% end %>
<%= @item.errors.messages if @item.errors.any?  %>

app/views/items/edit.html.erb
<%= render "form", item: @item %>

app/views/items/new.html.erb
<% if request.referer.include? "/shopping_list" %>
  <div class="shopping-new-container" data-controller="shopping-list-form">
    <%= simple_form_for @item, data: { shopping_list_form_target: "existingItems"} do |f| %>
      <%= f.input :id, label: "Select an existing item:", collection: @existing_items, label_method: :name, value_method: :id, prompt: "Select an item" %>
      <%= hidden_field_tag :previous_page, request.referer %>
      <%= f.submit %>
    <% end %>
    <button class="btn accent-gradient" data-action="shopping-list-form#revealForm" data-shopping-list-form-target="button">New item</button>
    <div class="d-none" data-shopping-list-form-target="newForm">
      <%= render "form", item: @item%>
    </div>
  </div>
<% else %>
  <%= render "form", item: @item %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PantryAi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/profile.html.erb
<%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>

app/views/pantries/show.html.erb
<h1>Pantry show</h1>
<%= link_to "+ Item", new_item_path %>
 <p><%= @pantry.items.count %> items</p>
<ul>
  <% @pantry.items.each do |item| %>
    <%= render "shared/item_card", item: item %>
  <% end %>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_item_card.html.erb
<li><%= item.name %> || <%= link_to "edit", edit_item_path(item) %> ||
    <%= link_to "delete",
      item_path(item),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure? Item will also be removed from the shopping list"}
    %>
    <% if params[:controller] == "pantries"  %>
      <%= link_to "add to shopping list", add_to_list_path(item), data: { turbo_method: :patch } %>
    <% end %>
</li>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Pantry", pantry_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Shopping List", shopping_list_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shopping_lists/show.html.erb
<h1>This is my shopping list</h1>
<%= link_to "+ item", new_item_path %>
<ul>
  <% @shopping_list.items.each do |item| %>
    <%= render "shared/item_card", item: item %>
  <% end %>
</ul>